### ISSUE TITLE
Print Templates

### ISSUE THREAD

**Issue by JJAM2019** [renderpci/dedalo#37] opened 2021-03-17 10:36 UTC
Dear all, 

Recently, we updated Dedalo to the version 5.7.77 of the product. 
After that, the custom print templates add option is missing.

We already reviewed the privileges of the role and everything about that is OK.

![Layout_tool](https://user-images.githubusercontent.com/16013864/111454439-ebcb5880-8714-11eb-9756-55ff7ce9b1d8.JPG)

**Comment by renderpci** [comment] 2021-03-17 10:44
Duplicate of #38

**Closed** 2021-03-22 21:49 UTC
Labels: bug
